import { Category, Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  // --- CONFECTIONERY (Торты, пирожные, рулеты) ---
  {
    id: '1',
    name: 'Медовик Классический',
    description: 'Традиционные медовые коржи с нежным сметанным кремом. Наш фирменный рецепт с 2016 года.',
    price: 2500,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.CONFECTIONERY,
    tags: ['classic', 'bestseller'],
    isPopular: true,
  },
  {
    id: '2',
    name: 'Наполеон с Ягодами',
    description: 'Множество тончайших слоеных коржей с заварным кремом и прослойкой из свежей малины.',
    price: 2800,
    image: 'https://images.unsplash.com/photo-1626264039818-6878c7731726?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.CONFECTIONERY,
    tags: ['classic', 'fruit'],
    isPopular: true,
  },
  {
    id: '3',
    name: 'Меренговый Рулет',
    description: 'Невесомая меренга с хрустящей корочкой, нежным кремом и свежей малиной. Тает во рту.',
    price: 1900,
    image: 'https://images.unsplash.com/photo-1629895056930-c3d6c07df747?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.CONFECTIONERY,
    tags: ['gluten-free', 'bestseller'],
    isPopular: true,
  },
  {
    id: '4',
    name: 'Чизкейк Сан-Себастьян',
    description: 'Баскский обожженный чизкейк с карамелизованной корочкой и кремовой серединкой.',
    price: 3200,
    image: 'https://images.unsplash.com/photo-1662580757753-3f8c5b9676c8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.CONFECTIONERY,
    tags: ['trend', 'cheese'],
  },
  {
    id: '5',
    name: 'Торт "Тирамису"',
    description: 'Итальянская классика в авторском исполнении. Савоярди, маскарпоне и эспрессо.',
    price: 2900,
    image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.CONFECTIONERY,
    tags: ['coffee', 'classic'],
  },
  {
    id: '6',
    name: 'Шоколадный Трюфель',
    description: 'Насыщенный шоколадный бисквит с ганашом из бельгийского шоколада.',
    price: 3200,
    image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.CONFECTIONERY,
    tags: ['chocolate'],
  },
  {
    id: '7',
    name: 'Пирожное "Шу" с Клубникой',
    description: 'Воздушное заварное тесто кракелин, ванильный крем и свежая клубника.',
    price: 350,
    image: 'https://images.unsplash.com/photo-1612203985729-70726954388c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.CONFECTIONERY,
    tags: ['french'],
  },

  // --- BAKERY (Пироги, булочки, слойки, пирожки) ---
  {
    id: '10',
    name: 'Песочный Пирог с Вишней',
    description: 'Рассыпчатое песочное тесто с щедрой начинкой из кисло-сладкой вишни.',
    price: 1200,
    image: 'https://images.unsplash.com/photo-1562007908-17c6742e3f8c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.BAKERY,
    tags: ['fruit', 'tea'],
  },
  {
    id: '11',
    name: 'Слойка с Орехом',
    description: 'Золотистое слоеное тесто с начинкой из грецкого ореха и карамели.',
    price: 180,
    image: 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.BAKERY,
    tags: ['nuts'],
  },
  {
    id: '12',
    name: 'Кольцо с Арахисом',
    description: 'Песочное кольцо, щедро обсыпанное жареным арахисом. Вкус детства.',
    price: 150,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.BAKERY,
    tags: ['nuts', 'classic'],
  },
  {
    id: '13',
    name: 'Пирожок с Капустой',
    description: 'Пышный печеный пирожок с сочной начинкой из молодой капусты и яйца.',
    price: 90,
    image: 'https://images.unsplash.com/photo-1621255767292-19e4811a243c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.BAKERY,
    tags: ['snack', 'savory'],
  },

  // --- EASTERN SWEETS (Пахлава, пальчики, печенья) ---
  {
    id: '20',
    name: 'Пахлава Медовая',
    description: '40 слоев тончайшего теста фило, грецкий орех и натуральный мед.',
    price: 1500,
    image: 'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.EASTERN_SWEETS,
    tags: ['nuts', 'honey', 'bestseller'],
    isPopular: true,
  },
  {
    id: '21',
    name: 'Орешки со Сгущенкой',
    description: 'Классическое песочное печенье в форме ореха с вареной сгущенкой.',
    price: 650,
    image: 'https://images.unsplash.com/photo-1630403756763-8a355694c7b8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.EASTERN_SWEETS,
    tags: ['classic', 'kids'],
  },
  {
    id: '22',
    name: 'Фисташковое Печенье',
    description: 'Мягкое печенье с трещинками (Crinkle) на основе фисташковой муки.',
    price: 800,
    image: 'https://images.unsplash.com/photo-1599599810769-bcde5a823097?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.EASTERN_SWEETS,
    tags: ['nuts', 'green'],
  },

  // --- CULINARY (Первые и вторые блюда, салаты, гарниры) ---
  {
    id: '30',
    name: 'Салат Цезарь с Курицей',
    description: 'Салат айсберг, черри, пармезан, гренки, филе цыпленка и фирменный соус.',
    price: 450,
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.CULINARY,
    tags: ['salad', 'lunch'],
  },
  {
    id: '31',
    name: 'Борщ с Говядиной',
    description: 'Наваристый домашний борщ. Подается со сметаной.',
    price: 390,
    image: 'https://images.unsplash.com/photo-1573333514797-815460950339?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.CULINARY,
    tags: ['soup', 'hot'],
  },
  {
    id: '32',
    name: 'Котлеты По-киевски',
    description: 'Куриная котлета с маслом и зеленью в панировке. С картофельным пюре.',
    price: 520,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.CULINARY,
    tags: ['main', 'dinner'],
  },

  // --- SEMI-FINISHED (Пельмени, котлеты, голубцы, вареники) ---
  {
    id: '40',
    name: 'Пельмени "Домашние"',
    description: 'Ручная лепка. Свинина-говядина. Тонкое тесто. Заморозка.',
    price: 850,
    image: 'https://images.unsplash.com/photo-1519624021569-45bcc71d533b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.SEMI_FINISHED,
    tags: ['frozen', 'meat'],
  },
  {
    id: '41',
    name: 'Вареники с Вишней',
    description: 'Сладкие вареники с цельной ягодой. Заморозка.',
    price: 700,
    image: 'https://images.unsplash.com/photo-1628205240224-b52c002166cb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.SEMI_FINISHED,
    tags: ['frozen', 'sweet'],
  },
  {
    id: '42',
    name: 'Голубцы Мясные',
    description: 'Капуста, рис, фарш. Готовы к тушению. Упаковка 1 кг.',
    price: 650,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: Category.SEMI_FINISHED,
    tags: ['frozen', 'dinner'],
  },
];

export const NAV_LINKS = [
  { name: 'Главная', path: '/' },
  { name: 'Меню', path: '/menu' },
  { name: 'О нас', path: '/about' },
  { name: 'Контакты', path: '/contact' },
];